version: '3.4'

x-backend:
  &backend
  build:
    context: .
  environment:
    RAILS_ENV: development
    DB_USERNAME: rails
    DB_PASSWORD: root
    DB_HOST: db
    DB_PORT: 5432
    DB_NAME: halter_development
    SECRET_KEY_BASE: STUB
  restart: on-failure:3
  stdin_open: true
  tty: true
  volumes:
    - .:/backend:rw
    - bundle_cache:/bundle

services:
  backend:
    <<: *backend
    ports:
      - 3000:3000/tcp
    depends_on:
      - db

  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: root
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  bundle_cache:
  postgres: