default: &default
  adapter: postgresql
  encoding: utf8
  username: rails
  password: root
  host: db
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: halter_development


test:
  <<: *default
  database: halter_test

production:
  <<: *default
  database: halter_production